# Generated by Django 4.0.6 on 2022-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('controlCodeResult', models.CharField(max_length=100)),
                ('installmentDate', models.CharField(max_length=8)),
                ('insuredName', models.CharField(max_length=100)),
                ('paymentStatus', models.CharField(max_length=100)),
                ('policyNo', models.CharField(max_length=100)),
            ],
        ),
    ]
